version: 2.1

orbs:
  unity-ci: mizotake/unity-ci@0.0.1

executors:
  unity_executor:
    docker:
      - image: gableroux/unity3d:2019.1.0f2

jobs:
  setup:
    machine: true
    steps:
      - restore_cache:
          key: unity-license-{{ checksum "ProjectSettings/ProjectVersion.txt" }}
  teardown:
    machine: true
    steps:
      - attach_workspace:
          at: /activateTools
      - save_cache:
          key: unity-license-{{ checksum "ProjectSettings/ProjectVersion.txt" }}
          paths:
            - /activateTools/Unity.ulf

workflows:
  version: 2
  unity-ci-test:
    jobs:
      - unity-ci/build:
          name: Build Execute Win
          exec: unity_executor
          platform: Win
          method: Build.Method
          zip: true
      - unity-ci/build:
          name: Build Execute WebGL
          exec: unity_executor
          platform: WebGL
          method: Build.Method
          zip: true
      - unity-ci/build:
          name: Build Execute OSXUniversal
          exec: unity_executor
          platform: OSXUniversal
          method: Build.Method
          zip: true
      - unity-ci/test:
          name: Edit Mode Test
          exec: unity_executor
          mode: editmode
      - unity-ci/test:
          name: Play Mode Test
          exec: unity_executor
          mode: playmode
      - unity-ci/execute_method:
          name: Exeucte Method
          exec: unity_executor
          method: Execute.Method
  unity-ci-activate-ulf-file:
    jobs:
      - setup
      - unity-ci/outputAlf:
          exec: unity_executor
          requires:
            - setup
      - unity-ci/cloneActivateTool:
          requires:
            - unity-ci/outputAlf
      - unity-ci/outputUlf:
          requires:
            - unity-ci/cloneActivateTool
      - unity-ci/execute_method:
          requires:
            - unity-ci/outputUlf
          name: Exeucte Method
          exec: unity_executor
          method: Execute.Method
      - teardown:
          requires:
            - unity-ci/execute_method
