version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.4
  orb-tools: circleci/orb-tools@8.27.4
  unity-ci: mizotake/unity-ci@dev:0.0.1
  slack: circleci/slack@3.3.0

executors:
  unity_executor:
    docker:
      - image: gableroux/unity3d:2019.1.0f2

commands:
  setup:
    description: "Unity Test Setup"
    steps:
      - run:
          name: craete project
          command: |
            /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -createProject ./
            cp -pR ./ci-test-tools/* ./Assets/
          working_directory: .

jobs:
  test-for-orb:
    executor: cli/default
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: curl cirlceci local
          command: |
            circleci config pack src > uncompiled-test-config.yml
            circleci config process uncompiled-test-config.yml > test-config.yml
            mv -f test-config.yml .circleci/config.yml
            circleci local execute -e UNITY_LICENSE_BASE64=UNITY_LICENSE_BASE64 --job unity-ci-build-webgl

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - orb-tools/lint
      - test-for-orb:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          name: publish dev orb
          requires:
            - test-for-orb
          orb-path: src/orbs/unity-ci.yml
          orb-name: mizotake/unity-ci
          sha-version-ref: dev:0.0.1
          checkout: true
          publish-alpha-version: false
          filters:
            branches:
              ignore: master
      - slack/approval-notification:
          requires:
            - test-for-orb
          message: "本番環境へのデプロイを承認してください"
          mentions: "here"
          color: "#F5E911"
          filters:
            branches:
              only: master
      - approve_deploy:
          type: approval
          requires:
            - slack/approval-notification
          filters:
            branches:
              only: master
      - orb-tools/dev-promote-prod:
          name: publish orb
          orb-name: mizotake/unity-ci
          orb-ref: dev:0.0.1
          requires:
            - approve_deploy
          filters:
            branches:
              only: master
