version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.4

executors:
  unity_executor:
    docker:
      - image: gableroux/unity3d:2019.1.0f2

commands:
  unity_activate:
    description: "Write Text File"
    parameters:
      license:
        description: "Unity License"
        type: env_var_name
        default: UNITY_LICENSE_BASE64
    steps:
      - run:
          name: activate
          command: |
            apt update && apt install cl-base64 -y
            echo ${<< parameters.license >>} | base64 -di | tr -d '\r' > Unity.ulf

jobs:      
  test-for-orb:
    executor: unity_executor
    steps:
      - checkout
      - run:
          name: curl cirlceci local
          command: |
            curl -fLSs https://circle.ci/cli | bash
            circleci config pack src
      - unity-ci-build-windows

workflows:
  version: 2
  deploy:
    jobs:
      - test-for-orb
      # - orb-tools/test-in-builds:
      #     requires: 
      #       - orb-tools/pack
      #     attach-workspace: true
      #     orb-location: src/orb.yml
      #     orb-name: unity-ci
      #     test-steps:
      #       - orb-tools/local-test-build:
      #           test-config-location: src/test/unity-ci-test.yml
      - orb-tools/publish:
          requires:
            - test-for-orb
          orb-path: src/orb.yml
          orb-ref: mizotake/unity-ci@dev:0.0.1
          validate: true
      #     filters:
      #       branches:
      #         ignore: master
      # - orb-tools/increment:
      #     orb-path: src/orb.yml
      #     orb-ref: mizotake/unity-ci
      #     segment: patch
      #     checkout: false
      #     # requires: [orb-tools/test-in-builds]
      #     filters:
      #       branches:
      #         only: master
      # - orb-tools/publish:
      #     orb-path: src/orb.yml
      #     orb-ref: mizotake/unity-ci
      #     requires: [orb-tools/increment]
      #     filters:
      #       branches:
      #         only: master