version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.4
  unity-ci: mizotake/unity-ci@dev:feature/orb

executors:
  unity_executor:
    docker:
      - image: gableroux/unity3d:2019.1.0f2

workflows:
  version: 2
  deploy:
    jobs:
      - orb-tools/test-in-builds:
          orb-location: .circleci/orb.yml
          orb-name: unity-ci
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: .circleci/test/unity-ci-test.yml
      - orb-tools/publish:
          orb-path: .circleci/orb.yml
          orb-ref: mizotake/unity-ci@dev:${CIRCLE_BRANCH}
          validate: true
          requires: [orb-tools/test-in-builds]
          filters:
            branches:
              ignore: master
      - orb-tools/increment:
          orb-path: .circleci/orb.yml
          orb-ref: mizotake/unity-ci
          segment: patch
          checkout: false
          requires: [orb-tools/test-in-builds]
          filters:
            branches:
              only: master
      - orb-tools/publish:
          orb-path: .circleci/orb.yml
          orb-ref: mizotake/unity-ci
          requires: [orb-tools/increment]
          filters:
            branches:
              only: master
      - unity-ci/build:
          requires: [orb-tools/publish]
          name: Build Execute Win
          exec: unity_executor
          license: UNITY_LICENSE_BASE64
          platform: Win
          method: Build.Execute
          zip: true
      - unity-ci/build:
          requires: [orb-tools/publish]
          name: Build Execute WebGL
          exec: unity_executor
          license: UNITY_LICENSE_BASE64
          platform: WebGL
          method: Build.Execute
          zip: true
      - unity-ci/build:
          requires: [orb-tools/publish]
          name: Build Execute OSXUniversal
          exec: unity_executor
          license: UNITY_LICENSE_BASE64
          platform: OSXUniversal
          method: Build.Execute
          zip: true
      - unity-ci/test:
          requires: [orb-tools/publish]
          name: Edit Mode Test
          exec: unity_executor
          license: UNITY_LICENSE_BASE64
          mode: editmode
      - unity-ci/test:
          requires: [orb-tools/publish]
          name: Play Mode Test
          exec: unity_executor
          license: UNITY_LICENSE_BASE64
          mode: playmode