version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.4
  unity-ci: mizotake/unity-ci@dev:0.0.1

executors:
  unity_executor:
    docker:
      - image: gableroux/unity3d:2019.1.0f2

workflows:
  version: 2
  unity-ci-build:
    jobs:
      - unity-ci/build:
          name: Build Execute Win
          exec: unity_executor
          platform: Win
          method: Build.Execute
          zip: true
          directory: ./Build/
      - unity-ci/build:
          name: Build Execute WebGL
          exec: unity_executor
          platform: WebGL
          method: Build.Execute
          zip: true
          directory: ./Build/
      - unity-ci/build:
          name: Build Execute OSXUniversal
          exec: unity_executor
          platform: OSXUniversal
          method: Build.Execute
          zip: true
          directory: ./Build/
  unity-ci-test:
    jobs:
      - unity-ci/test:
          name: Edit Mode Test
          exec: unity_executor
          mode: editmode
      - unity-ci/test:
          name: Play Mode Test
          exec: unity_executor
          mode: playmode
  deploy:
    jobs:
      - orb-tools/pack:
          source-dir: src/
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml
          validate: true
      - orb-tools/test-in-builds:
          requires: [orb-tools/pack]
          attach-workspace: true
          orb-location: src/orb.yml
          orb-name: unity-ci
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: src/test/unity-ci-test.yml
      - orb-tools/publish:
          orb-path: src/orb.yml
          orb-ref: mizotake/unity-ci@dev:0.0.1
          validate: true
          # requires: [orb-tools/test-in-builds]
      #     filters:
      #       branches:
      #         ignore: master
      # - orb-tools/increment:
      #     orb-path: src/orb.yml
      #     orb-ref: mizotake/unity-ci
      #     segment: patch
      #     checkout: false
      #     # requires: [orb-tools/test-in-builds]
      #     filters:
      #       branches:
      #         only: master
      # - orb-tools/publish:
      #     orb-path: src/orb.yml
      #     orb-ref: mizotake/unity-ci
      #     requires: [orb-tools/increment]
      #     filters:
      #       branches:
      #         only: master