version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.4
  orb-tools: circleci/orb-tools@8.27.4

executors:
  unity_executor:
    docker:
      - image: gableroux/unity3d:2019.1.0f2

jobs:
  test-for-orb:
    executor: cli/default
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: curl cirlceci local
          command: |
            circleci config pack src > uncompiled-test-config.yml
            cat uncompiled-test-config.yml
            circleci config process uncompiled-test-config.yml > test-config.yml
            circleci local execute -c test-config.yml -e UNITY_LICENSE_BASE64=UNITY_LICENSE_BASE64 --job "unity-ci-build-webgl"

workflows:
  version: 2
  deploy:
    jobs:
      - orb-tools/lint
      - test-for-orb:
          requires:
            - orb-tools/lint
      - orb-tools/publish:
          requires:
            - test-for-orb
          orb-path: src/orb.yml
          orb-ref: mizotake/unity-ci@dev:0.0.1
          validate: true
      #     filters:
      #       branches:
      #         ignore: master
      # - orb-tools/increment:
      #     orb-path: src/orb.yml
      #     orb-ref: mizotake/unity-ci
      #     segment: patch
      #     checkout: false
      #     # requires: [orb-tools/test-in-builds]
      #     filters:
      #       branches:
      #         only: master
      # - orb-tools/publish:
      #     orb-path: src/orb.yml
      #     orb-ref: mizotake/unity-ci
      #     requires: [orb-tools/increment]
      #     filters:
      #       branches:
      #         only: master
