version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.4

executors:
  unity_executor:
    docker:
      - image: gableroux/unity3d:2019.1.0f2

jobs:      
  test-for-orb:
    executor: unity_executor
    steps:
      - checkout
      - run:
          name: curl cirlceci local
          command: |
            apt update && apt install curl -y
            curl -fLSs https://circle.ci/cli | bash
            circleci config pack src > test-config.yml
                        circleci config pack src > uncompiled-test-config.yml
            circleci config process uncompiled-test-config.yml > test-config.yml
            circleci local execute -c test-config.yml -e UNITY_LICENSE_BASE64=UNITY_LICENSE_BASE64

workflows:
  version: 2
  deploy:
    jobs:
      - test-for-orb
      - orb-tools/publish:
          requires:
            - test-for-orb
          orb-path: src/orb.yml
          orb-ref: mizotake/unity-ci@dev:0.0.1
          validate: true
      #     filters:
      #       branches:
      #         ignore: master
      # - orb-tools/increment:
      #     orb-path: src/orb.yml
      #     orb-ref: mizotake/unity-ci
      #     segment: patch
      #     checkout: false
      #     # requires: [orb-tools/test-in-builds]
      #     filters:
      #       branches:
      #         only: master
      # - orb-tools/publish:
      #     orb-path: src/orb.yml
      #     orb-ref: mizotake/unity-ci
      #     requires: [orb-tools/increment]
      #     filters:
      #       branches:
      #         only: master