version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.4
  orb-tools: circleci/orb-tools@8.27.4
  unity-ci: mizotake/unity-ci@dev:0.0.1

executors:
  unity_executor:
    docker:
      - image: gableroux/unity3d:2019.1.0f2

commands:
  setup:
    description: "Unity Test Setup"
    steps:
      - run:
          name: craete project
          command: |
            /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -createProject .
            cp -pR ./ci-test/* ./Assets/
          working_directory: .

jobs:
  unity-ci-build-windows:
    executor: unity_executor
    steps:
      - checkout
      - unity-ci/unity_activate
      - setup
      - unity-ci/build:
          platform: Win
          method: Build.Execute
      - unity-ci/zip:
          directory: ./Build/
      - store_artifacts:
          path: ./Build/
  unity-ci-build-webgl:
    executor: unity_executor
    steps:
      - checkout
      - unity-ci/unity_activate
      - setup
      - unity-ci/build:
          platform: WebGL
          method: Build.Execute
      - unity-ci/zip:
            directory: ./Build/
      - store_artifacts:
          path: ./Build/
  unity-ci-build-osxuniversal:
    executor: unity_executor
    steps:
      - checkout
      - unity-ci/unity_activate
      - setup
      - unity-ci/build:
          platform: OSXUniversal
          method: Build.Execute
      - unity-ci/zip:
            directory: ./Build/
      - store_artifacts:
          path: ./Build/
  unity-ci-test-editmode:
    executor: unity_executor
    steps:
      - checkout
      - unity-ci/unity_activate
      - setup
      - unity-ci/test:
          mode: editmode
  unity-ci-test-playmode:
    executor: unity_executor
    steps:
      - checkout
      - unity-ci/unity_activate
      - setup
      - unity-ci/test:
          mode: playmode
  test-for-orb:
    executor: cli/default
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: curl cirlceci local
          command: |
            circleci config pack src > uncompiled-test-config.yml
            circleci config process uncompiled-test-config.yml > test-config.yml
            cat test-config.yml
            circleci local execute --config test-config.yml -e UNITY_LICENSE_BASE64=UNITY_LICENSE_BASE64 --job unity-ci-build-webgl

workflows:
  version: 2
  deploy:
    jobs:
      - orb-tools/lint
      - unity-ci-build-webgl:
          requires:
            - orb-tools/lint
      # - test-for-orb:
      #     requires:
      #       - orb-tools/lint
      # - orb-tools/publish:
      #     requires:
      #       - test-for-orb
      #     orb-path: src/orbs/unity-ci.yml
      #     orb-ref: mizotake/unity-ci@dev:0.0.1
      #     validate: true
      #     filters:
      #       branches:
      #         ignore: master
      # - orb-tools/increment:
      #     orb-path: src/orb.yml
      #     orb-ref: mizotake/unity-ci
      #     segment: patch
      #     checkout: false
      #     # requires: [orb-tools/test-in-builds]
      #     filters:
      #       branches:
      #         only: master
      # - orb-tools/publish:
      #     orb-path: src/orb.yml
      #     orb-ref: mizotake/unity-ci
      #     requires: [orb-tools/increment]
      #     filters:
      #       branches:
      #         only: master
