
jobs:
  build:
    parameters:
      exec:
        type: executor
      license:
        description: "Unity License"
        type: env_var_name
        default: UNITY_LICENSE_BASE64
      method:
        description: "Build Execute Method"
        type: string
      platform:
        description: "Test Target Platform"
        type: string
      zip:
        description: "Archive Build Contents"
        default: false
        type: boolean
      no_output_timeout:
        description: "No Output Timeout"
        type: string
        default: 10m
      directory:
        description: "Target Directory"
        type: string
        default: .
    executor: << parameters.exec >>
    steps:
      - checkout
      - unity_activate:
          license: << parameters.license >>
      - build:
          platform: << parameters.platform >>
          method: << parameters.method >>
          no_output_timeout: << parameters.no_output_timeout >>
      - when:
          condition: << parameters.zip >>
          steps:
            - zip:
                directory: << parameters.directory >>
      - store_artifacts:
          path: << parameters.directory >>
  test:
    parameters:
      exec:
        type: executor
      license:
        description: "Unity License"
        type: env_var_name
        default: UNITY_LICENSE_BASE64
      mode:
        description: "Test Target Mode"
        type: string
    executor: << parameters.exec >>
    steps:
      - checkout
      - unity_activate:
          license: << parameters.license >>
      - test:
          mode: << parameters.mode >>
      - store_test_results:
          path: ./test-results
  execute_method:
    parameters:
      exec:
        type: executor
      license:
        description: "Unity License"
        type: env_var_name
        default: UNITY_LICENSE_BASE64
      method:
        description: "Build Execute Method"
        type: string
    executor: << parameters.exec >>
    steps:
      - checkout
      - unity_activate:
          license: << parameters.license >>
      - execute_method:
          method: << parameters.method >>
