name: unity-ci-example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:2019.1.0f2
    steps:
    - uses: actions/checkout@master
    - name: Unity Activate
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" --output ./Unity.ulf ./Unity.ulf.gpg
        /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile Unity.ulf || exit 0
    - name: Create Empty Project
      run: |
        /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -createProject ./
        cp -pR ./ci-test-tools/* ./Assets/
    - name: Build
      env:
        PLATFORM: Win
        METHOD: Build.Execute
      run: |
        /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod $METHOD -buildTarget $PLATFORM
